repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      # Run Ruff to lint all issues and apply auto-fixes.
      - id: ruff
        name: ruff
        entry: ruff
        args: ["check", "--fix", "."]
        language: python
        types_or: [python, pyi, jupyter]
        exclude: ^migrations/
      # Run Ruff to check and fix import issues only.
      - id: ruff
        name: ruff-imports
        entry: ruff
        args: ["check", "--select", "I", "--fix", "."]
        language: python
        types_or: [python, pyi, jupyter]
        exclude: ^migrations/
      # Run Ruff to apply formatting only.
      - id: ruff
        name: ruff-format
        entry: ruff
        args: ["format", "."]
        language: python
        types_or: [python, pyi, jupyter]
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["--exclude", "tests/,test_*,*tests.py"]
        exclude: ^migrations/
