services:
  api:
    build:
      context: .
    # env_file: .env
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
